### ISSUE TITLE
Bezels should be ontop of themes

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#15]
Bezels should be ontop of themes.

**Comment by pcca-matrix** [comment]
We discussed it on discord, I cannot without removing the bezel from the background animation.
removing the bezel from the animation does not look good since it stay static between the background transition.

**Comment by Yaron2019** [comment]
I remember talking about it and you brought up rewriting that shader but I guess you tried and it doesn't look good.
No problem.

**Comment by Yaron2019** [comment]
I played around with your code on my PC (no commits of course). Here is how it looks with the bezels on top.
After all, when we consider the need for bezels in the first place - it is intended only for users with wide screen displays who want to run the themes in their native 4:3 aspect ratio. A user with a 4:3 screen doesn't need bezels
Second thing to take into account is that much of the artwork was created with the idea in mind the the artifacts will be off-screen in the first place and will not be seen.

With the bezels on top there are far less visual artifacts and the transitions look fine IMO - we can differ here as I am not a native HS user.

Here is the hacked code, very little changes that needs to be incorporated properly if applied:
[layout.zip](https://github.com/pcca-matrix/PCCA-Layout/files/4863529/layout.zip)

Here is a video demo of it in action:
https://youtu.be/CGHDgOE7yZQ

Tell me what you think my friend! :)

**Comment by pcca-matrix** [comment]
exactly , but it's not smooth when you have a mix of hyperspin theme, hd and video theme in full res.

what I'm going to do is an option to let the user choose between full transition or partial bezel transition.

 

partial transition, will be in fact as currently, but at the end of the background transition , a static bezel image will be put on top of the existing bezel incrusted in background. 

in this way, this will mask the artwork that exceeds without disturbing too much the transitions when you switch between differents theme res.

 

I will do this later because it involves modifying the shader and i must modify it first for the probleme with small overlay.

 

 

Sent from my iPhone

 

De : Yaron2019 [mailto:notifications@github.com] 
Envoyé : jeudi 2 juillet 2020 12:28
À : pcca-matrix/PCCA-Layout
Cc : pcca-matrix; Comment
Objet : Re: [pcca-matrix/PCCA-Layout] Bezels should be ontop of themes (#15)

 

I played around with your code on my PC (no commits of course). Here is how it looks with the bezels on top.
After all, when we consider the need for bezels in the first place - it is intended only for users with wide screen displays who want to run the themes in their native 4:3 aspect ratio. A user with a 4:3 screen doesn't need bezels
Second thing to take into account is that much of the artwork was created with the idea in mind the the artifacts will be off-screen in the first place and will not be seen.

With the bezels on top there are far less visual artifacts and the transitions look fine IMO - we can differ here as I am not a native HS user.

Here is the hacked code, very little changes that needs to be incorporated properly if applied:
layout.zip <https://github.com/pcca-matrix/PCCA-Layout/files/4863529/layout.zip> 

Here is a video demo of it in action:
https://youtu.be/CGHDgOE7yZQ

Tell me what you think my friend! :)

**Comment by Yaron2019** [comment]
I catch your drift.
In the meanwhile I am playing around with your layout script, making the wheel pointer and current wheel logo fade as well.
It looks good. I have a few ideas to add for the options menu but first we get rid of the current issues which are more important.

**Comment by Yaron2019** [comment]
I've updated to the latest version and the bezels are indeed on top. There are two small issues:
1. When you first enter the theme from the main menu it doesn't load anything but the current wheel logo
2. The bezels pop on-top of the theme which is very noticeable in some themes. You can see narrow bezels and then it loads a wider bezel the "covers" the edges of the theme hence the popping effect.

I'm sure you have a reason to do the bezels like you did but I don't understand why we don't just place the bezels graphics on-top of the theme and call it a day. I mean just load it after the snap in the layout script or give it a higher zorder? I did it in my themes and it works..

**Comment by Yaron2019** [comment]
Look at the character's right side of the body at the bottom left - when the game theme loads it is shown and then the bezels pops ontop of it.

https://youtu.be/uwZOS-5z9fk

**Comment by pcca-matrix** [comment]
yes it's because the bezels are added later ...
maybe I'll add a 3rd bezel option, "fixed bezel" for those who do not mix 4/3 and hd themes.

**Comment by Yaron2019** [comment]
Good idea. BTW - the bezels that load later also cut the corners of the themes - it's evident in the default mame theme.

![Capture](https://user-images.githubusercontent.com/52970692/90328722-9c4d6000-df6c-11ea-94d5-4cd6f8fd26ad.JPG)

**Comment by Yaron2019** [comment]
Resolved!
