### ISSUE TITLE
theme.xml ?

### ISSUE THREAD

**Issue by lechatz** [pcca-matrix/PCCA-Layout#55]
Hello,

First time for me on attract mode and also with this great theme.

1) In the wiki that say : "It's possible to add to your artwork xml tags: width and height for auto resizing media artwork.

example: <artwork3 w="550" h="280" x="777" y="417" time="0.7" delay ="0" type="ease" start="right" rest="none"/> "

Where precisely I have to put this line ? I didn't find any xml on pcca folder. And almost all my media are too big.

2) is it normal that from one system to another the artwork folder changes, example for snes the folder is artwork1 for nes the folder is artwork 3, etc. It's not very serious, but confusing enough for a beginner like me, to understand why nothing is displayed

Thx

**Comment by pcca-matrix** [comment]
Hi,

Ex : your Theme.xml 

` <artwork1 x="312" y="427" r="0" time="1" delay ="0.5" type="none" start="none" rest="none"/>`

Add width and height 

` <artwork1 w="500" h="250" x="312" y="427" r="0" time="1" delay ="0.5" type="none" start="none" rest="none"/>`
 
Yes it's normal,  it comes from the hyperspin themes you are using, not from the pcca layout, the artwork number is not always the same because hyperspin themes is created by different people.

But you can easily change them by renaming the artwork number also in the Theme.xml

**Comment by pcca-matrix** [comment]
I close the issue since it is not a problem with the layout itself.
