### ISSUE TITLE
does not work correctly  with attract mode plus 

### ISSUE THREAD

**Issue by shiryu55** [pcca-matrix/PCCA-Layout#62]
It would be possible to adapt it to work correctly with the am plus

**Comment by pcca-matrix** [comment]
Unfortunately, no !
 
Since AM+ no longer supports flash animations and the zip_get_dir function has been modified, i cannot make them compatible again without breaking Hyperspin compatibility, which is the primary goal of this theme.

and also there is an incompatibility with the theme internal scraper (soon available on the public version)

sad because AM+ is a good fork...

Maybe if I have time in the future, i'll make a version compatible with AM+ but it is not on my priority list.
